name: GlobalMute
description: Mute the global chat! Meaning no one will be able to chat.
main: shelly7w7\globalmute\GlobalMute
version: 2.0.0
api: 4.0.0
author: Shelly7w7

commands:
  global:
    description: Enable/Disable Global Mute.
    aliases: ["gm"]
    permission: global.mute

permissions:
 global.mute:
  default: op
