name: GlobalMute
description: Mute the global chat! Meaning no one will be able to chat.

main: shelly7w7\globalmute\GlobalMute
version: 1.0.1
api: 3.0.0

author: Shelly7w7

commands:
  globalmute:
    aliases: [gm]
    description: Enable/Disable Global Mute.
    permission: global.mute